# Getting Started with the Command Line

## Executing a Command-line Tool

Now that you have a basic understanding of the environment, it is high time that you try out some commands. Type the following in your terminal (without the dollar sign) and press `<Enter>`:

```{bash, eval=FALSE}
 pwd
```

Sometimes we are using commands and pipelines that are too long to fit on the page. In that case you’ll see something like the following:

```{bash, eval=FALSE}
echo 'Hello'\
 ' world' |
 wc
```

The greater-than sign is the continuation prompt, which indicates that this line is a continuation of the previous one. A long command can be broken up with either a backslash or a pipe symbol. Be sure to first match any quotation marks. The following command is exactly the same:

```{bash, eval=FALSE}
echo 'Hello world' | wc
```

This is as simple as it gets. You just executed a command that contained a single command-line tool. The command-line tool `pwd` [@pwd] prints the name of the directory where you currently are. By default, when you login, this is your home directory. You can view the contents of this directory with `ls` [@ls]:

```{bash, eval=FALSE}
 ls
```

The command-line tool `cd`, which is a Bash builtin, allows you to navigate to a different directory:

```{bash, eval=FALSE}
 cd book/ch02/
 cd data
 pwd
/home/vagrant/book/ch02/data
 cd ..
 pwd
/home/vagrant/book/ch02/
```

The part after `cd` specifies to which directory you want to navigate to. Values that come after the command are called command-line arguments or options. The two dots refer to the parent directory. Let’s try a different command:

```{bash, eval=FALSE}
 head -n 3 data/movies.txt
Matrix
Star Wars
Home Alone
```

Here we pass three command-line arguments to `head` [@head]. The first one is an option. The second one is a value that belongs to the option. The third one is a filename. This particular command outputs the first three lines of file *book/ch02/data/movies.txt*.

### Five Types of Command-line Tools

We employ the term command-line tool a lot, but so far, we have not yet explained what we actually mean by it. We use it as an umbrella term for *anything* that can be executed from the command line. Under the hood, each command-line tool is one of the following five types:

- A binary executable.
- A shell builtin.
- An interpreted script.
- A shell function.
- An alias.

It’s good to know the difference between the types. The other three types (interpreted script, shell function, and alias) allow us to further build up our data science toolbox and become more efficient and more productive data scientists.

### Binary Executable

Binary executables are programs in the classical sense. A binary executable is created by compiling source code to machine code. This means that when you open the file in a text editor you cannot read it.

### Shell Builtin

Shell builtins are command-line tools provided by the shell, which is Bash in our case. Examples include `cd` and `help`. These cannot be changed. Shell builtins may differ between shells. Like binary executables, they cannot be easily inspected or changed.

### Interpreted Script

An interpreted script is a text file that is executed by a binary executable. Examples include: Python, R, and Bash scripts. One great advantage of an interpreted script is that you can read and change it. Example \@ref(exm:script-fac) shows a script named *\~/book/ch02/fac.py*. This script is interpreted by Python not because of the file extension *.py*, but because the first line of the script defines the binary that should execute it.

    ```{example script-fac, name="Python script that computes the factorial of an integer"}
    ```
    ```{python, eval=FALSE}
    ##!/usr/bin/env python
    def factorial(x):
        result = 1
        for i in xrange(2, x + 1):
            result *= i
        return result
    if __name__ == "__main__":
        import sys
        x = int(sys.argv[1])
        print factorial(x)
    ```

    This script computes the factorial of the integer that we pass as a parameter. It can be invoked from the command line as follows:

    ```{bash, eval=FALSE}
     book/ch02/fac.py 5
    120
    ```

    
### Shell Function

A shell function is a function that is, in our case executed by Bash. They provide similar functionality to a Bash script, but they are usually (but not necessarily) smaller than scripts. They also tend to be more personal. The following command defines a function called `fac`, which, just like the interpreted Python script above, computes the factorial of the integer we pass as a parameter. It does by generating a list of numbers using `seq`, putting those numbers on one line with `*` as the delimiter using `paste` [@paste], and passing this equation into `bc` [@bc], which is evaluates it and outputs the result.

    ```{bash, eval=FALSE}
     fac() { (echo 1; seq 1) | paste -s -d\* - | bc; }
     fac 5
    120
    ```

The file *.bashrc*, which is a configuration file for Bash, is a good place to define your shell functions, so that they are always available.

### Alias

Aliases are like macros. If you often find yourself executing a certain command with the same parameters (or a part of it), you can define an alias for this. Aliases are also very useful when you continue to misspell a certain command (see <https://github.com/chrishwiggins/mise/blob/master/sh/aliases-public.sh> for a long list of useful aliases). The following command defines such an alias:

    ```{bash, eval=FALSE}
     alias l='ls -1 --group-directories-first'
     alias moer=more
    ```

Now, if you type the following on the command line, the shell will replace each alias it finds with its value:

    ```{bash, eval=FALSE}
     cd ~
     l
    book
    ```


## Combining Command-line Tools

Because most command-line tools adhere to the UNIX philosophy, they are designed to do only thing, and do it really well. For example, the command-line tool `grep` [@grep] can filter lines, `wc` [@wc] can count lines, and `sort` [@sort] can sort lines. The power of the command line comes from its ability to combine these small, yet powerful command-line tools. The most important way of combining command-line tools is through a so-called pipe. The output from the first tool is passed to the second tool. There are virtually no limits to this.

Consider, for example, the command-line tool `seq`, which generates a sequence of numbers. Let us generate a sequence of five numbers.

```{bash, eval=FALSE}
 seq 5
```

The output of a command-line tool is by default passed on to the terminal, which displays it on our screen. We can *pipe* the ouput of `seq` to a second tool, called `grep`, which can be used to filter lines. Imagine that we only want to see numbers that contain a "3". We can combine `seq` and `grep` as follows:

```{bash, eval=FALSE}
 seq 30 | grep 3
```

And if we wanted to know *how many* numbers between 1 and 100 that contain a three, we can use `wc`, that is very good at counting things:

```{bash, eval=FALSE}
 seq 100 | grep 3 | wc -l
```

The option `-l` specifies that `wc` should only output the number of lines that are pass into it. By default it also returns the number of characters and words.

You may start to see that combining command-line tools is a very powerful concept. In the rest of the book you will be introduced to many more tools and the functionality they offer when combining them.

## Redirecting Input and Output

We mentioned that, by default, the output of the last command-line tool in the pipeline is outputted to the terminal. You can also save this output to a file. This is called output redirection, and works as follows:

```{bash, eval=FALSE}
 seq 10 > data/ten-numbers
```

Here, we save the output of the `seq` tool to a file named *ten-numbers* in the directory *\~/book/ch02/data*. If this file does not exist yet, it is created. If this file already did exist, its contents would have been overwritten. You can also append the output to a file with `>>`, meaning the output is put after the original contents:

```{bash, eval=FALSE}
 echo -n "Hello" > hello-world
 echo " World" >> hello-world
```

The tool echo just outputs the value you specify. The `-n` option specifies that `echo` should not output a trailing newline.

Saving the output to a file is useful if you need to store intermediate results, for example for continuing with your analysis at a later stage. To use the contents of the file *hello-world* again, we can use `cat` [@cat], which reads a file prints it.

```{bash, eval=FALSE}
 cat hello-world | wc -w
```

(Note that the `-w` option indicates `wc` to only count words.) The same result can be achieved with the following notation:

```{bash, eval=FALSE}
 < hello-world wc -w
```

This way, you are directly passing the file to the standard input of `wc` without running an additional process. If the command-line tool also allows files to be specified as command-line arguments, which many do, you can also do the following for `wc`:

```{bash, eval=FALSE}
 wc -w hello-world
```

## Working With Files

As data scientists, we work with a lot of data. This data is often stored in files. It is important to know how to work with files (and the directories they live in) on the command line. Every action that you can do using a graphical user interface, you can do with command-line tools (and much more). In this section we introduce the most important ones to create, move, copy, rename, and delete files and directories.

You have already seen how we can create new files by redirecting the output with either `>` or `>>`. In case you need to move a file to a different directory you can use `mv` [@mv]:

```{bash, eval=FALSE}
 mv hello.txt ~/book/ch02/data/
```

You can also rename files with `mv`:

```{bash, eval=FALSE}
 cd data
 mv hello.txt bye.txt
```

You can also rename or move entire directories. In case you no longer need a file, you delete (or remove) it with `rm` [@rm]:

```{bash, eval=FALSE}
 rm bye.txt
```

In case you want to remove an entire directory with all its contents, specify the `-r` option, which stands for recursive:

```{bash, eval=FALSE}
 rm -r book/ch02/data/old
```

In case you want to copy a file, use `cp` [@cp]. This is useful for creating backups:

```{bash, eval=FALSE}
 cp server.log server.log.bak
```

You can create directories using `mkdir` [@mkdir]:

```{bash, eval=FALSE}
 cd data
 mkdir logs
```

Using the command-line tools to manage your files can be scary at first, because you have no graphical overview of the file system to provide immediate feedback.

All of the above command-line tools accept the `-v` option, which stands for verbose, so that they output what’s going on. All but `mkdir` accept the `-i` option, which stands for interactive, and causes the tools to ask you for confirmation.

## Help

As you are finding your way around the command-line, it may happen that you need help. Even the most-seasoned Linux users need help at some point. It is impossible to remember all the different command-line tools and their possible arguments. Fortunately, the command line offers severals ways to get help.

The most important command to get help is perhaps `man` [@man], which is short for *manual*. It contains information for most command-line tools. Imagine that we forgot the different options to the tool `cat`. You can access its man page using:

```{bash, eval=FALSE}
 man cat | head -n 20
```

```{block2, type="rmdtip"}
Sometimes you’ll see us use `head`, `fold`, or `cut` at the end of a command. This is only to ensure that the output of the command fits on the page; you don’t have to type these. For example, `head -n 5` only prints the first five lines, `fold` wraps long lines to 80 characters, and `cut -c1-80` trims lines that are long than 80 characters.
```

Not every command-line tool has a man page. For shell builtins, such as `cd`, you need to use the `help` command-line tool:

```{bash, eval=FALSE}
 help cd | head -n 20
```

This help also covers other topics of Bash, in case you are interested (try `help` without command-line arguments for a list of topics). Remember that you can use `type` to figure out the kind of a specific command-line tool.

Newer tools that can be used from the command-line, often lack a man page as well. In that case, your best bet is to invoke the tool with the `--help` option (and sometimes the `-h` option). For example:

```{bash, eval=FALSE}
jq --help
```

Specifying the `--help` option also works for the GNU command-line tools such as `cat`. However, the corresponding man page often provides more information. If, after trying these three approaches, you are still stuck, then it is perfectly acceptable to consult the Internet. In the appendix, there’s a list of all command-line tools used in this book. Besides how each command-line tool can be installed, it also shows how you can get help.
