--- 
title: "Predictive Analytics"
author: "Markum Reed"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This course aims to go beyond the classical statistical methods. As computing power has increased many new, highly computational, regression, or “Machine Learning”, methods have been developed. There has been a significant expansion of the number of possible approaches. Since these methods are so new, the business community is generally unaware of their huge potential. With the explosion of “Big Data” problems, machine learning has become a hot field in many scientific areas as well as marketing, finance and other business disciplines. People with machine learning skills are in high demand."
---

# Predictive Analytics

This course aims to go beyond the classical statistical methods. As computing power has increased many new, highly computational, regression, or “Machine Learning”, methods have been developed. There has been a significant expansion of the number of possible approaches. Since these methods are so new, the business community is generally unaware of their huge potential. With the explosion of “Big Data” problems, machine learning has become a hot field in many scientific areas as well as marketing, finance and other business disciplines. People with machine learning skills are in high demand.


### Course Text

In this course we will be following [James, Gareth, et al. An introduction to statistical learning. Vol. 112. New York: springer, 2013.](https://statlearning.com/ISLR%20Seventh%20Printing.pdf).

### Course Material
  | **Course Material**                           | **Reading Assignment** | **Labs**                                                                | **Due Date** |
  |-----------------------------------------------|------------------------|-------------------------------------------------------------------------|--------------|
  | [Course Introduction]                         |                        |                                                                         |              |
  | [Review Material]                             |                        |                                                                         |              |
  | [Statistical Learning]                        | Ch. 1,2                |                                                                         |              |
  | [Linear Regression: Theory]                   | Ch. 3                  |                                                                         |              |
  | [Linear Regression: Practice]                 |                        | [Lab: Linear Regression]                                                |              |
  | [Classification: Theory]                      | Ch. 4                  |                                                                         |              |
  | [Classification: Practice]                    |                        | [Lab: Logistic Regression]   [Lab: KNN]                                 |              |
  | [Resampling: Theory]                          | Ch. 5                  |                                                                         |              |
  | [Resampling: Practice]                        |                        | [Lab: Cross-Validation and the Bootstrap]                               |              |
  | [Linear Model Selection and Regularization: Theory]   | Ch. 6                  |                                                                         |              |
  | [Linear Model Selection and Regularization: Practice]   |                        | [Lab: Subset Selection Methods]   [Lab: Elastic Net Regression]         |              |
  | [Tree Based Methods: Theory]                  | Ch. 8                  |                                                                         |              |
  | [Tree Based Methods: Practice]                |                        | [Lab: Decision Trees]                                                   |              |
  | [Support Vector Machines: Theory]             | Ch. 9                  |                                                                         |              |
  | [Support Vector Machines: Practice]                     |                        | [Lab: Support Vector Machines]                                          |              |
  | [Unsupervised Learning: Theory]               | Ch. 10                 |                                                                         |              |
  | [Unsupervised Learning: Practice]             |                        | [Lab: Principal Components Analysis]   [Lab: Clustering]                |              |
